name: Apply Ruleset to Main Branch

on:
  workflow_dispatch: {}

jobs:
  apply_ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Apply ruleset using GitHub API
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Applying ruleset to $REPO_NAME"

          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${REPO_NAME}/rulesets \
            -d '{
              "name": "Protect Main",
              "target": "branch",
              "enforcement": "active",
              "conditions": {
                "ref_name": {
                  "include": ["main"],
                  "exclude": []
                }
              },
              "rules": [
                {
                  "type": "pull_request",
                  "parameters": {
                    "require_approving_review_count": 1,
                    "require_code_owner_review": false,
                    "dismiss_stale_reviews_on_push": false
                  }
                },
                {
                  "type": "linear_history",
                  "parameters": {}
                }
              ]
            }')

          BODY=$(echo "$RESPONSE" | head -n -1)
          STATUS=$(echo "$RESPONSE" | tail -n1)

          echo "---------------------------"
          echo "HTTP STATUS: $STATUS"
          echo "RESPONSE BODY:"
          echo "$BODY"
          echo "---------------------------"
