name: Apply Ruleset to Main Branch

on:
  workflow_dispatch:

jobs:
  apply_ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Apply ruleset using GitHub API
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Target Repository: $REPO_NAME"
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${REPO_NAME}/rulesets \
            -d '{
              "name": "Protect Main",
              "target": "branch",
              "enforcement": "active",
              "conditions": {
                "ref_name": {
                  "include": ["main"],
                  "exclude": []
                }
              },
              "rules": [
                {
                  "type": "required_pull_request_reviews",
                  "parameters": {
                    "required_approving_review_count": 1,
                    "dismiss_stale_reviews": false,
                    "require_code_owner_review": false
                  }
                },
                {
                  "type": "non_fast_forward",
                  "parameters": {}
                }
              ]
            }'

